services:
  postgres:
    image: postgres:15-alpine
    container_name: ticketbox-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ticketbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketbox_db
    networks:
      - ticketbox-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.7
    container_name: ticketbox-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=ticketbox_master_key
      - MEILI_ENV=development
    networks:
      - ticketbox-network

  redis:
    image: redis:7-alpine
    container_name: ticketbox-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - ticketbox-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ticketbox-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ticketbox-network

  mongodb:
    image: mongo:latest
    container_name: ticketbox-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - ticketbox-network
    volumes:
      - mongodata:/data/db

  # auth-service:
  #   build: .
  #   image: ticketbox-api
  #   container_name: ticketbox-auth-service
  #   networks:
  #     - ticketbox-network
  #   environment:
  #     - SERVICE_NAME=auth
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=ticketbox
  #     - DB_PASSWORD=password
  #     - DB_NAME=ticketbox_db
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/ticketbox_db?authSource=admin
  #     - REDIS_HOST=redis
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - redis
  #     - rabbitmq

  # booking-service:
  #   build: .
  #   image: ticketbox-api
  #   container_name: ticketbox-booking-service
  #   networks:
  #     - ticketbox-network
  #   environment:
  #     - SERVICE_NAME=booking
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=ticketbox
  #     - DB_PASSWORD=password
  #     - DB_NAME=ticketbox_db
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/ticketbox_db?authSource=admin
  #     - REDIS_HOST=redis
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - redis
  #     - rabbitmq

  # info-service:
  #   build: .
  #   image: ticketbox-api
  #   container_name: ticketbox-info-service
  #   networks:
  #     - ticketbox-network
  #   environment:
  #     - SERVICE_NAME=info
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=ticketbox
  #     - DB_PASSWORD=password
  #     - DB_NAME=ticketbox_db
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/ticketbox_db?authSource=admin
  #     - REDIS_HOST=redis
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #   restart: always
  #   depends_on:
  #     - postgres
  #     - mongodb
  #     - redis
  #     - rabbitmq

  nginx:
    image: nginx:alpine
    container_name: ticketbox-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ticketbox-network

networks:
  ticketbox-network:
    driver: bridge

volumes:
  pgdata:
  mongodata:

